### ISSUE TITLE
Ensure correct IPs within HPI and elsewhere

### ISSUE THREAD

**Issue by Bouncner** [hpi-epic/pricewars#14]
I just removed the network from the `docker-compose.yml` as it caused errors in certain cases within the HPI.

As even the default docker network caused errors, we need to fix the docker daemon for all HPI machines. As soon as this is done, there is no need to have the network re-definition within the compose file.

Anyhow, we should make sure that this setup works out anywhere, not just within the HPI.

**Comment by Bouncner** [comment]
I had to revert. There appears to be no easy way to tell docker to use the default bridge settings for container-owned networks.

**Comment by CarstenWalther** [comment]
The default bridge network `bridge` (`docker0`) is a legacy component and Docker does not recommend to use it in production. Additionally, the default bridge network uses the IP range 172.17.0.0/16, which conflicts with the HPI network.

That's why we use a custom bridge network. We can configure it as needed.
As far as I know, the best IP range to use is a private IP range.
We should choose an IP range so that conflicts with the host's network are unlikely.
However, it is not possible to completely avoid such conflicts for all setups.
